name: Build and release Qt/qtbase

on: 
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Qt
      run: |
        choco install qt5-default
        dir C:\Qt\5.15.2
        setx QMAKE "C:\Qt\5.15.2\mingw81_64\bin\qmake.exe"
        
    - name: Build Qt/qtbase
      run: |
        qmake -config static
        nmake
        
    - name: Package files
      uses: TheDoctor0/zip-release@0.6.2
      with:
        files: |
          **/*.dll
          **/*.lib
          **/*.exe
        name: qtbase-${{ github.run_id }}
        
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.run_id }}
        draft: false
        prerelease: false
        
    - name: Upload assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: qtbase-${{ github.run_id }}.zip
        asset_name: qtbase-${{ github.run_id }}.zip
        asset_content_type: application/zip
